# Unique name for this workflow
name: CI

# Definition when the workflow should run
on:
    workflow_dispatch:
    push:
        branches:
            - main
            - v*
        paths-ignore:
            - 'sfdx-project.json'
            - 'README.md'